export const GET_TASK_LIST = 'GET_TASK_LIST';
export const ADD_TASK_LIST_GROUP = 'ADD_TASK_LIST_GROUP';
export const UPDATE_TASK_LIST = 'UPDATE_TASK_LIST';
export const UPDATE_TASK_AT_GROUP = 'UPDATE_TASK_AT_GROUP';
export const DELETE_TASK_ITEM = 'DELETE_TASK_ITEM';
